config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'

  get '/contact' => 'site#contact'

  resources :projects, only: [:index, :show] do
    resources :entries, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  #Todo esto ya no es necesario dado que las
  #3 líneas de arriba realizan el mismo trabajo
  #Haz un rake routes para ver todas las rutas
  # get '/projects' => 'projects#index'

  # get '/projects/:id' => 'projects#show'

  # get '/projects/:project_id/entries' => 'entries#index'

  # get '/projects/:project_id/entries/new' => 'entries#new'
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :hours, :minutes, numericality: true
  validates :hours, :minutes, :date, presence: true
  #Con el de abajo chequeas si está asociado a un proyecto
  validates :project_id, presence:true

  belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
has_many :entries

# validates :name, description: true
# validates :name, presence: true
# validates :name, uniqueness: true
# validates :name, length: {maximum: 30}
# validates :name, format: {with: /[a-zA-ZÑñ0-9\ ]+\z/}

  def self.iron_find(id)
    #Project.
    where(id: id).first
  end

  def self.clean_old
    where('created_at < ?', Time.now - 1.week).destroy_all
  end

  def self.last_created_projects(number)
    order(created_at: :desc).limit(number)
  end

  #Método que nos devuelve la suma de horas trabajadas
  def total_hours_in_month(month, year)
    from = Date.new(year, month, 1)
    to = from.end_of_month
    
    entries = self.entries.where(date: from..to)
    # Crea un array y te suma todas las horas de cada uno de
    # los elementos del array
    entries.to_a.sum(&:hours)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @projects = Project.last_created_projects(10)
  end

  def render_404(params)
    Rails.logger.warn("Tried to access #{params[:id]} which did not exist.")
    render "/layouts/404"
  end
  

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    #Recoge todos los parama
    @project =Project.find params[:project_id]
    @entries = @project.entries

    date = Date.today
    @current_month_hours = @project.total_hours_in_month(date.month, date.year)
    # @current_month_hours = Project.find[:hours]
  end

  def show
    @project = Project.find params [:id]
  end
  #Muestra formulario de crear
  def new
    #El project_id viene a través de la uri
    @project = Project.find params[:project_id]
    #Inicializas la entrada
    @entry = @project.entries.new
  end

  def create
    #Find the project
    @project = Project.find params[:project_id]
    #New entry for that project with attributes from params[:entry]
    @entry = @project.entries.new entry_params
    #Try to save it
    if@entry.save
      redirect_to action: :index, project_id: @project.id
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @entry = @project.entries.find(params[:id])
  end

  def update
    #Find the project
    @project = Project.find(params[:project_id])
    #FInd the entry for that project with attributes from params[:id]
    @entry = @project.entries.find(params[:id])
    #Try to save it
    if @entry.update_attributes entry_params
      redirect_to action: 'index'
    else  
      render 'edit'
    end
  end

  #Aquí buscamos una entry y la borramos
  def destroy
    #No hace falta el @ porque no lo vamos a devolver a una vista
    project = Project.find(params[:project_id])
    entry = project.entries.find(params[:id])
    #entry
    entry.destroy

    redirect_to action: :index, project_id: project.id
  end

  private

  # def project
  #   @_project ||= Project.find(params[:project_id])
  # end

  #Con este método filtro a través de los strong parameters
  #que no accedan más variables de las que yo quiero
  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created_projects(10)
    if @projects.empty?
      render 'site/no_project'
    end
  end

  def show
    @project = Project.find_by(id: params[:id]) || render_404(params)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    #render 'home'
  end

  def contact
    #render 'contact'
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/edit.html.erb
<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours, size: 4 %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes, size: 4 %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date, size: 4 %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', project_entries_path(@project) %>
<% end %>

app/views/entries/index.html.erb
<h1><%= @project.name %></h1>
<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= entry.hours %> h
      <%= entry.minutes %>m
      <%= entry.date.to_date %> -
      <%= link_to 'Edit', edit_project_entry_path(@project, entry) %>
      <%= link_to('Delete', project_entry_path(@project, entry), method: :delete,data:{confirm: 'Are you sure?'}) %>
    </li>
    <%end%>
</ul>

<%= link_to 'Projects', projects_path %>
<%= link_to 'New Entry', new_project_entry_path(@project) %>



<!-- @current_month_hours lo definimos en el controlador del proyecto-->
<p> The total hours worked this month is: <%= @current_month_hours %></p>

app/views/entries/new.html.erb
<% if @entry.errors.any? %>
  <ul>
    <% @entry.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <br>

  <%= f.submit 'Save' %>
<%end%>

<%= link_to 'Back to entries', project_entries_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      <h1>Time tracking tool</h1>
    </header>
<!-- El yield pertenece a projects/index.html.erb -->
<%= yield %>
  <footer>
    Ironhack - Rails introduction
  </footer>
  </div>
</body>
</html>

app/views/layouts/error404.html.erb
<p>Something went wrong </p>

app/views/projects/error.html.erb
<p>Project name: <&= @project.name %></p>
<p>Project description: <&= @project.description %></p>

app/views/projects/index.html.erb
<h1>Your projects</h1>

<ul>
  <% @projects.each do |project| %>
  <li><%= link_to(project.name, project_entries_path(project)) %>
    <% if project.description.present? %>
      <%= "-#{project.description}" %>
    <%end %>
  </li>
  <%end %>
</ul>

app/views/projects/show.html.erb
<p>Project name: <%= params[:id] %></p>
<p>Project name: <%= @project.name %></p>
<p>Project description: <%= @project.description %></p>

app/views/site/contact.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Timetracking tool</title>
</head>
<body>
  <h1> Insert your email address please: contact@example.com </h1>
  <p>Ironhack powered</p>
</body>
</html>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>

<p>Send me an email to contact@example.com</p>

app/views/site/index.html.erb
<h1>Aquí están tus proyectos</h1>
<ul>
  <% @projects.each do |project| %>
    <li>
      <%= project.name %>
      <% unless project.description.blank? %>
        <%= " - #{project.description}" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/site/no_project.html.erb
<h1>You have no projects</h1>
  